version: "3.3"

services:
  hello-world-php:
    build: .
    ports:
      - "8081:80"
    labels:
      - "traefik.http.routers.hello-world-php.rule=Host(`hello-world-php.localhost`)"
    depends_on:
      - traefik
  traefik:
    image: traefik:v2.9
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"